### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by adrianmihalko** [andrewatwood/homeAppFrontend#1]
Hi,

I am trying to run the app, but I get error:

```
npm ERR! Linux 4.4.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! HomeFrontEnd@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the HomeFrontEnd@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the HomeFrontEnd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls HomeFrontEnd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homeAppFrontend/npm-debug.log
```

**Comment by adrianmihalko** [comment]
missed: npm install

**Comment by andrewatwood** [comment]
Figured that was it. Glad you figured it out!

**Comment by adrianmihalko** [comment]
The project is super, I hope you continue development for more switches/devices (selector switch, sensors, etc).

**Comment by andrewatwood** [comment]
Thanks! I plan to. What all types of device would you need?

**Comment by adrianmihalko** [comment]
I am still planning my home system with Domoticz. At this time I have simple on-off switches, selector switches, dimmer, sensors (temperature, thermostat, barometer, humidity, lux, etc).

Definitely it needs more tweaking, but at this time I see only one on-off switch if I open homeAppFrontend (the LED switch on the image above).

Here is a screenshot about my current Domoticz frontpage:

<img width="1264" alt="screen-shot-2016-09-20-22-54-47" src="https://cloud.githubusercontent.com/assets/733361/18688714/d1541906-7f85-11e6-8202-1c15c40c3e3e.png">

My 2nd room /heating/:

<img width="1280" alt="screen-shot-2016-09-20-23-00-57" src="https://cloud.githubusercontent.com/assets/733361/18688796/33281920-7f86-11e6-9853-26197571c7c5.png">

In homeAppFrontend I see only the relay (whitch is a on/off switch).
